BEGIN;

CREATE TYPE user_status AS ENUM ('ACTIVE', 'ON_LEAVE', 'DISABLED');
CREATE TYPE device_type AS ENUM ('DESKTOP', 'LAPTOP', 'TABLET', 'PHONE', 'MONITOR');
CREATE TYPE device_status AS ENUM ('IN_STOCK', 'ASSIGNED', 'REPAIR', 'RETIRED');
CREATE TYPE incident_priority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE incident_status AS ENUM ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');
CREATE TYPE incident_source AS ENUM ('PORTAL', 'PHONE', 'EMAIL', 'MONITORING');
CREATE TYPE assignment_role AS ENUM ('PRIMARY', 'SECONDARY', 'ESCALATION');

CREATE TABLE departments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_department_id integer REFERENCES departments (id) ON DELETE SET NULL,
  code varchar(12) NOT NULL UNIQUE,
  name varchar(100) NOT NULL UNIQUE,
  cost_center varchar(20) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT departments_code_format CHECK (code ~ '^[A-Z][A-Z0-9_]{2,11}$'),
  CONSTRAINT departments_not_self_parent CHECK (parent_department_id IS NULL OR parent_department_id <> id)
);

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id integer NOT NULL REFERENCES departments (id) ON DELETE RESTRICT,
  employee_number varchar(20) NOT NULL UNIQUE,
  full_name varchar(120) NOT NULL,
  email varchar(254) NOT NULL UNIQUE,
  status user_status NOT NULL DEFAULT 'ACTIVE',
  location varchar(80) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT users_email_lowercase CHECK (email = lower(email)),
  CONSTRAINT users_email_shape CHECK (position('@' IN email) > 1)
);

CREATE TABLE devices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assigned_user_id bigint REFERENCES users (id) ON DELETE SET NULL,
  asset_tag varchar(30) NOT NULL UNIQUE,
  serial_number varchar(80) NOT NULL UNIQUE,
  hostname varchar(63) UNIQUE,
  type device_type NOT NULL,
  status device_status NOT NULL,
  manufacturer varchar(80) NOT NULL,
  model varchar(100) NOT NULL,
  operating_system varchar(100),
  purchase_date date NOT NULL,
  warranty_until date,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT devices_assignment_consistent CHECK (
    (status = 'ASSIGNED' AND assigned_user_id IS NOT NULL)
    OR status <> 'ASSIGNED'
  ),
  CONSTRAINT devices_warranty_after_purchase CHECK (
    warranty_until IS NULL OR warranty_until >= purchase_date
  )
);

CREATE TABLE technicians (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id integer NOT NULL REFERENCES departments (id) ON DELETE RESTRICT,
  employee_number varchar(20) NOT NULL UNIQUE,
  full_name varchar(120) NOT NULL,
  email varchar(254) NOT NULL UNIQUE,
  skill_level smallint NOT NULL,
  skills text[] NOT NULL DEFAULT '{}',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT technicians_skill_level_range CHECK (skill_level BETWEEN 1 AND 5),
  CONSTRAINT technicians_email_lowercase CHECK (email = lower(email))
);

CREATE TABLE sla_policies (
  priority incident_priority PRIMARY KEY,
  response_target interval NOT NULL,
  resolution_target interval NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT sla_targets_positive CHECK (
    response_target > interval '0 seconds'
    AND resolution_target > response_target
  )
);

INSERT INTO sla_policies (priority, response_target, resolution_target)
VALUES
  ('LOW', interval '8 hours', interval '72 hours'),
  ('MEDIUM', interval '4 hours', interval '24 hours'),
  ('HIGH', interval '1 hour', interval '8 hours'),
  ('CRITICAL', interval '15 minutes', interval '2 hours');

CREATE TABLE incidents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  device_id bigint REFERENCES devices (id) ON DELETE SET NULL,
  title varchar(200) NOT NULL,
  description text NOT NULL,
  category varchar(60) NOT NULL,
  service_name varchar(80) NOT NULL,
  priority incident_priority NOT NULL,
  status incident_status NOT NULL DEFAULT 'OPEN',
  source incident_source NOT NULL,
  first_response_at timestamptz,
  sla_deadline timestamptz NOT NULL,
  resolved_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  search_document tsvector GENERATED ALWAYS AS (
    to_tsvector(
      'english'::regconfig,
      coalesce(title, '') || ' ' || coalesce(description, '') || ' ' || coalesce(category, '')
    )
  ) STORED,
  CONSTRAINT incidents_title_not_blank CHECK (btrim(title) <> ''),
  CONSTRAINT incidents_description_not_blank CHECK (btrim(description) <> ''),
  CONSTRAINT incidents_sla_after_creation CHECK (sla_deadline > created_at),
  CONSTRAINT incidents_response_after_creation CHECK (
    first_response_at IS NULL OR first_response_at >= created_at
  ),
  CONSTRAINT incidents_resolution_state_consistent CHECK (
    (status IN ('RESOLVED', 'CLOSED') AND resolved_at IS NOT NULL)
    OR (status IN ('OPEN', 'IN_PROGRESS') AND resolved_at IS NULL)
  ),
  CONSTRAINT incidents_closed_state_consistent CHECK (
    (status = 'CLOSED' AND closed_at IS NOT NULL)
    OR (status <> 'CLOSED' AND closed_at IS NULL)
  ),
  CONSTRAINT incidents_resolution_after_creation CHECK (
    resolved_at IS NULL OR resolved_at >= created_at
  ),
  CONSTRAINT incidents_close_after_resolution CHECK (
    closed_at IS NULL OR (resolved_at IS NOT NULL AND closed_at >= resolved_at)
  )
);

CREATE TABLE incident_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id bigint NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
  author_user_id bigint REFERENCES users (id) ON DELETE SET NULL,
  author_technician_id integer REFERENCES technicians (id) ON DELETE SET NULL,
  body text NOT NULL,
  is_internal boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT incident_comments_one_author CHECK (
    num_nonnulls(author_user_id, author_technician_id) = 1
  ),
  CONSTRAINT incident_comments_body_not_blank CHECK (btrim(body) <> '')
);

CREATE TABLE software (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor varchar(100) NOT NULL,
  name varchar(120) NOT NULL,
  latest_version varchar(40) NOT NULL,
  support_ends_on date,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT software_vendor_name_unique UNIQUE (vendor, name),
  CONSTRAINT software_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT software_version_not_blank CHECK (btrim(latest_version) <> '')
);

CREATE TABLE software_installations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id bigint NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
  software_id integer NOT NULL REFERENCES software (id) ON DELETE CASCADE,
  installed_version varchar(40) NOT NULL,
  installed_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT software_installations_device_software_unique UNIQUE (device_id, software_id),
  CONSTRAINT software_installations_version_not_blank CHECK (btrim(installed_version) <> ''),
  CONSTRAINT software_installations_seen_after_install CHECK (last_seen_at >= installed_at)
);

CREATE TABLE incident_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id bigint NOT NULL REFERENCES incidents (id) ON DELETE CASCADE,
  technician_id integer NOT NULL REFERENCES technicians (id) ON DELETE RESTRICT,
  role assignment_role NOT NULL DEFAULT 'PRIMARY',
  assigned_at timestamptz NOT NULL,
  unassigned_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT incident_assignments_unique_role UNIQUE (incident_id, technician_id, role),
  CONSTRAINT incident_assignments_order CHECK (
    unassigned_at IS NULL OR unassigned_at >= assigned_at
  )
);

CREATE TABLE incident_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id bigint NOT NULL,
  changed_by text NOT NULL DEFAULT current_user,
  action varchar(20) NOT NULL,
  old_row jsonb,
  new_row jsonb,
  changed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT incident_audit_log_action CHECK (action IN ('UPDATE', 'DELETE'))
);

CREATE INDEX idx_departments_parent ON departments (parent_department_id);
CREATE INDEX idx_users_department ON users (department_id);
CREATE INDEX idx_devices_assigned_user ON devices (assigned_user_id);
CREATE INDEX idx_devices_type_status ON devices (type, status);
CREATE INDEX idx_technicians_department_active ON technicians (department_id, is_active);
CREATE INDEX idx_incidents_requester_created ON incidents (requester_user_id, created_at DESC);
CREATE INDEX idx_incidents_device_created ON incidents (device_id, created_at DESC);
CREATE INDEX idx_incidents_created_at ON incidents (created_at DESC);
CREATE INDEX idx_incident_comments_incident_created ON incident_comments (incident_id, created_at);
CREATE INDEX idx_installations_software ON software_installations (software_id);
CREATE INDEX idx_assignments_incident ON incident_assignments (incident_id);
CREATE INDEX idx_audit_incident_changed ON incident_audit_log (incident_id, changed_at DESC);

CREATE UNIQUE INDEX uq_active_primary_assignment
  ON incident_assignments (incident_id)
  WHERE role = 'PRIMARY' AND unassigned_at IS NULL;

COMMIT;
